# Generated by Django 5.0.6 on 2024-06-11 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=130)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("bio", models.TextField()),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="client_pictures/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Programmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=130)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("experience", models.IntegerField()),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("webdeveloper", "WebDeveloper"),
                            ("backenddeveloper", "BackendDeveloper"),
                            ("networking", "Networking"),
                            ("ai/machinelearning", "AI/MachineLearning"),
                            ("cloudservices", "CloudServices"),
                            ("admincustomersupport", "AdminCustomerSupport"),
                        ],
                        default="AI/MachineLearning",
                        max_length=50,
                    ),
                ),
                ("skills", models.TextField()),
                ("bio", models.TextField()),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="programmer_pictures/"
                    ),
                ),
                (
                    "categories",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Networking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.programmer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MachineLearning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.programmer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CloudServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.programmer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BackEndDeveloper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.programmer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminCustomerSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.programmer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebDeveloper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.programmer"
                    ),
                ),
            ],
        ),
    ]
